export class PPU {
    constructor(nes: NES);
    bus: NES;
    vblank: boolean;
    vram: Uint8Array;
    vramBank: Uint8Array[];
    oamPrimary: Uint8Array;
    oamSecondary: Uint8Array;
    oamAddress: number;
    oamIndex: number;
    palette: Uint8Array[];
    bkgPixelsBuffer: Uint32Array;
    sprPixelsBuffer: Uint32Array;
    bkgLayer: VideoBuffer;
    sprBehindLayer: VideoBuffer;
    sprInFrontLayer: VideoBuffer;
    sprLayer: VideoBuffer;
    sprite0Layer: Uint32Array;
    isPowered: boolean;
    powerOn(): void;
    set control(arg: number);
    set mask(arg: number);
    set status(arg: number);
    get status(): number;
    set OAMAddress(arg: number);
    set scroll(arg: number);
    set address(arg: number);
    set data(arg: number);
    get data(): number;
    ntsc: boolean;
    cpu: CPU;
    cart: Cartridge;
    output: VideoOutput;
    powerOff(): void;
    reset(): void;
    doVBlank(): void;
    endVBlank(): void;
    addressIncrement: number;
    sprPatternTable: number;
    bkgPatternTable: number;
    sprite8x16: boolean;
    nmiEnabled: boolean;
    spriteHeight: number;
    grayscale: boolean;
    showLeftMostBkg: boolean;
    showLeftMostSpr: boolean;
    showBackground: boolean;
    showSprites: boolean;
    emphasizeRed: boolean;
    emphasizeGreen: boolean;
    emphasizeBlue: boolean;
    renderingEnabled: boolean;
    writeToggle: boolean;
    spriteOverflow: boolean;
    sprite0Hit: boolean;
    sprite0: boolean;
    set OAMData(arg: number);
    get OAMData(): number;
    fineScrollY: number;
    fineScrollX: number;
    addressBuffer: number;
    addressBus: number;
    readBuffer: number;
    readRegister(address: number): number;
    writeRegister(address: number, data: number): void;
    read(address: number): number;
    write(address: number, data: number): void;
    get backdrop(): number;
    get bkgPalette(): Uint8Array;
    get sprPalette(): Uint8Array;
    readPalette(address: number): number;
    writePalette(address: number, data: number): void;
    incrementX(): void;
    incrementY(): void;
    resetX(): void;
    resetY(): void;
    fetchNameTable(bus: number): number;
    fetchAttributeTable(bus: number): number;
    fetchBkgPatternTable(patternIndex: number, row: number): number;
    fetchTile(): void;
    fetchNullTile(): void;
    fetchNullNTs(): void;
    renderTile(dot: number, scanline: number): void;
    clearSecondaryOAM(): void;
    evaluateSprites(scanline: number): void;
    fetchSprPatternTable(patternIndex: number, row: number): number;
    fetchSprite(scanline: number): void;
    fetchNullSprite(): void;
    renderSprite(scanline: number): void;
    setPatternPixels(target: number, pattern: number, palette: number, paletteIndex: number, flip: boolean): void;
    printFrame(): void;
}
export default PPU;
import { Cartridge } from "./Cartridges.js";
import CPU from "./CPU.js";
import NES from "./NES.js";
import VideoOutput, { VideoBuffer } from "./Video.js";
//# sourceMappingURL=PPU.d.ts.map